include:
  - project: 'wimma-lab-2023/mysticons/app-repo'
    file: '/templates/.conf.gitlab-ci.yml'

stages:
  - build
  - update

variables:
  IMAGE_TAG: $CI_COMMIT_SHA

build:
  extends:
    - .build
  tags:
    - general

update:
  extends:
    - .update
  tags:
    - general

