# docker-compose-frontend.yml
version: '3'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app-network
    ports:
      - 5173:80
    depends_on:
      - backend

networks:
  app-network:
