version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    networks:
      - app-network
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: skillcollector

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    networks:
      - app-network
    ports:
      - '3000:3000'
      - '443:443'
    depends_on:
      - postgres
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app-network
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  app-network:
